# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Lenovo/CLionProjects/Bookstore-2022

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Lenovo/CLionProjects/Bookstore-2022

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Lenovo/CLionProjects/Bookstore-2022/CMakeFiles /mnt/c/Users/Lenovo/CLionProjects/Bookstore-2022/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Lenovo/CLionProjects/Bookstore-2022/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named code

# Build rule for target.
code: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 code
.PHONY : code

# fast build rule for target.
code/fast:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/build
.PHONY : code/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/main.cpp.s
.PHONY : main.cpp.s

src/book.o: src/book.cpp.o

.PHONY : src/book.o

# target to build an object file
src/book.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/book.cpp.o
.PHONY : src/book.cpp.o

src/book.i: src/book.cpp.i

.PHONY : src/book.i

# target to preprocess a source file
src/book.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/book.cpp.i
.PHONY : src/book.cpp.i

src/book.s: src/book.cpp.s

.PHONY : src/book.s

# target to generate assembly for a file
src/book.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/book.cpp.s
.PHONY : src/book.cpp.s

src/diary.o: src/diary.cpp.o

.PHONY : src/diary.o

# target to build an object file
src/diary.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/diary.cpp.o
.PHONY : src/diary.cpp.o

src/diary.i: src/diary.cpp.i

.PHONY : src/diary.i

# target to preprocess a source file
src/diary.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/diary.cpp.i
.PHONY : src/diary.cpp.i

src/diary.s: src/diary.cpp.s

.PHONY : src/diary.s

# target to generate assembly for a file
src/diary.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/diary.cpp.s
.PHONY : src/diary.cpp.s

src/error.o: src/error.cpp.o

.PHONY : src/error.o

# target to build an object file
src/error.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/error.cpp.o
.PHONY : src/error.cpp.o

src/error.i: src/error.cpp.i

.PHONY : src/error.i

# target to preprocess a source file
src/error.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/error.cpp.i
.PHONY : src/error.cpp.i

src/error.s: src/error.cpp.s

.PHONY : src/error.s

# target to generate assembly for a file
src/error.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/error.cpp.s
.PHONY : src/error.cpp.s

src/strScanner.o: src/strScanner.cpp.o

.PHONY : src/strScanner.o

# target to build an object file
src/strScanner.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/strScanner.cpp.o
.PHONY : src/strScanner.cpp.o

src/strScanner.i: src/strScanner.cpp.i

.PHONY : src/strScanner.i

# target to preprocess a source file
src/strScanner.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/strScanner.cpp.i
.PHONY : src/strScanner.cpp.i

src/strScanner.s: src/strScanner.cpp.s

.PHONY : src/strScanner.s

# target to generate assembly for a file
src/strScanner.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/strScanner.cpp.s
.PHONY : src/strScanner.cpp.s

src/user.o: src/user.cpp.o

.PHONY : src/user.o

# target to build an object file
src/user.cpp.o:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/user.cpp.o
.PHONY : src/user.cpp.o

src/user.i: src/user.cpp.i

.PHONY : src/user.i

# target to preprocess a source file
src/user.cpp.i:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/user.cpp.i
.PHONY : src/user.cpp.i

src/user.s: src/user.cpp.s

.PHONY : src/user.s

# target to generate assembly for a file
src/user.cpp.s:
	$(MAKE) -f CMakeFiles/code.dir/build.make CMakeFiles/code.dir/src/user.cpp.s
.PHONY : src/user.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... code"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/book.o"
	@echo "... src/book.i"
	@echo "... src/book.s"
	@echo "... src/diary.o"
	@echo "... src/diary.i"
	@echo "... src/diary.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/strScanner.o"
	@echo "... src/strScanner.i"
	@echo "... src/strScanner.s"
	@echo "... src/user.o"
	@echo "... src/user.i"
	@echo "... src/user.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

